#!/bin/csh -f
#
# Update docs to public web site

foreach doc ( index.html logo101.gif ../*.gz \
	      manual/snl_2_0_man.{pdf,ps} \
	      manual/Manual*.{css,gif,html,pdf,ps} )
	echo $doc ...
	/bin/cp -p $doc ~www/public/realpublic/epics/seq
end

