State Notation Language
and Sequencer Users Guide
Version 2.0
(for EPICS release 3.13 and later)

Manual Revision 1.9 (DRAFT)
February 18, 1998
Written by Andy Kozubal
Instrumentation and Control Group
Dynamic Experimentation Division
Mail Stop P942
Los Alamos National Laboratory
Los Alamos, New Mexico 87545
Phone: (505) 667-6508
EMAIL: AKozubal@LANL.Gov

Manual Revision 2.0 (DRAFT 3)
February15, 2000
Updated by William Lupton
(with some material by Greg White)
W. M. Keck Observatory
65-1120 Mamalahoa Highway
Kamuela, Hawaii 96743
Phone: (808) 885 7887
EMAIL: WLupton@Keck.Hawaii.Edu
