/* xia_version.h -- DO NOT MODIFY
 *
 * This file is automatically generated by generate_version.pl
 */

#ifndef _XIA_VERSION_H_
#define _XIA_VERSION_H_

#define XERXES_MAJOR_VERSION   1
#define XERXES_MINOR_VERSION   0
#define XERXES_RELEASE_VERSION 3

#define HANDEL_MAJOR_VERSION   1
#define HANDEL_MINOR_VERSION   0
#define HANDEL_RELEASE_VERSION 3

#define VERSION_STRING         "release"

#endif /* _XIA_VERSION_H_ */

