/* xia_version.h -- DO NOT MODIFY (please)
 *
 * This file is automatically generated by 
 * XIA::Releaser.update_handel_version().
 */

#ifndef _XIA_VERSION_H_
#define _XIA_VERSION_H_

#define XERXES_MAJOR_VERSION 0
#define XERXES_MINOR_VERSION 6
#define XERXES_RELEASE_VERSION 47

#define HANDEL_MAJOR_VERSION 0
#define HANDEL_MINOR_VERSION 6
#define HANDEL_RELEASE_VERSION 47

#define VERSION_STRING "xmanager-release"

#endif /* _XIA_VERSION_H_ */

