int     CCDStartExposure();
int     CCDStopExposure();
char    *CCDStatus();
int     CCDState();
int     CCDSetFilePar(int which_par, const char *p_value);
int     CCDGetFilePar(int which_par, const char *p_value);
int     CCDSetHwPar(int which_par, const char *p_value);
int     CCDGetHwPar(int which_par, const char *p_value);
int     CCDSetBin(int val);
int     CCDGetBin();
int     CCDGetImage();
int     CCDCorrectImage();
int     CCDWriteImage();
char    *CCDGetLastError();
int     CCDAbort();
int     CCDReset();
int     CCDInitialize();
