TOP = ../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Products
PROD_HOST += 

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

