#Makefile one level down from top of application tree
TOP = ..
include $(TOP)/configure/CONFIG

#directories in which to build
DIRS += simple 
DIRS += validate
DIRS += demo

include $(TOP)/configure/RULES_DIRS

