TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#USR_CFLAGS += 
#USR_CXXFLAGS +=

INC += cbf.h img.h cbf_tree.h cbf_context.h cbf_file.h global.h md5.h
LIBRARY_IOC += marIpCBF
LIB_SRCS += cbf.c cbf_alloc.c cbf_ascii.c cbf_binary.c cbf_byte_offset.c cbf_canonical.c cbf_codes.c cbf_compress.c   
LIB_SRCS += cbf_context.c cbf_file.c cbf_lex.c cbf_packed.c cbf_predictor.c cbf_read_binary.c cbf_read_mime.ci
LIB_SRCS += cbf_string.c cbf_stx.c cbf_tree.c cbf_uncompressed.c cbf_write.c cbf_write_binary.c md5c.c 
#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

