TOP = ../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Products
PROD_HOST += misplacedExit sncExOpt_DuplOpt sncExOpt_UnrecOpt

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

